// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracer.Infrastructure.Persistence;

#nullable disable

namespace Tracer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TracerDbContext))]
    [Migration("20260306071245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tracer.Core.Entities.DeviceAlert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AcknowledgedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Status", "CreatedUtc");

                    b.ToTable("DeviceAlerts");
                });

            modelBuilder.Entity("Tracer.Core.Entities.DeviceObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Channel")
                        .HasColumnType("int");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FrequencyBand")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HardwareAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InterfaceName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsPaired")
                        .HasColumnType("bit");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ObservedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RawPayload")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("ScanBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ObservedUtc");

                    b.HasIndex("ScanBatchId");

                    b.ToTable("DeviceObservations");
                });

            modelBuilder.Entity("Tracer.Core.Entities.DiscoveredDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FrequencyBand")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HardwareAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaired")
                        .HasColumnType("bit");

                    b.Property<string>("LastInterfaceName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LastSignalStrength")
                        .HasColumnType("int");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RadioKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("TotalObservations")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceKey")
                        .IsUnique();

                    b.HasIndex("LastSeenUtc");

                    b.ToTable("DiscoveredDevices");
                });

            modelBuilder.Entity("Tracer.Core.Entities.ScanBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BluetoothDevices")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CompletedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScannerNode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TotalDevices")
                        .HasColumnType("int");

                    b.Property<int>("WifiDevices")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompletedUtc");

                    b.ToTable("ScanBatches");
                });

            modelBuilder.Entity("Tracer.Core.Entities.DeviceAlert", b =>
                {
                    b.HasOne("Tracer.Core.Entities.DiscoveredDevice", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Tracer.Core.Entities.DeviceObservation", b =>
                {
                    b.HasOne("Tracer.Core.Entities.DiscoveredDevice", "Device")
                        .WithMany("Observations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracer.Core.Entities.ScanBatch", "ScanBatch")
                        .WithMany("Observations")
                        .HasForeignKey("ScanBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("ScanBatch");
                });

            modelBuilder.Entity("Tracer.Core.Entities.DiscoveredDevice", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Tracer.Core.Entities.ScanBatch", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
